### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by Santinaker** [cuckydev/PSXFunkin#16]
Hello, I discovered this project thanks to Videogamesscz for porting this game to ps3, I was very impressed when I tried it, I wish you good luck, when it is complete I will definitely play it complete.
I'm excited about everything that can be done in the mods section
He also came to ask that they put the option of ghost tapping and the mapping of controls,also when you lose points the bar goes down very slow.
Greetings from Argentina and sorry if there is something wrong in my English, I translated it with Google

**Comment by cuckydev** [comment]
I'm not entirely sure about implementing ghost tapping, since I feel like that might make the game stray too far from a vanilla engine port, even with the kapi week. Same thing goes with the health bar, since the values are straight from the original game. As for mapping of controls, there's no other logical button mapping on the ps1 controller, so if you want to remap just use your emulator's settings or a different controller.
