### ISSUE TITLE
Issue with chart stopping

### ISSUE THREAD

**Issue by g3om3tryYT** [cuckydev/PSXFunkin#21]
Hello, I have been having issues with the charts stopping somewhere in the song and I don't know why. I use duckstation for my pc, and I have been trying to get it to work on Wiisxrx (wii/wii U port of pcsx) and I never got it to load the charts on wiisxrx.

**Comment by g3om3tryYT** [comment]
if you want I can record it happening

**Comment by g3om3tryYT** [comment]
https://user-images.githubusercontent.com/83846251/126854714-aeb57be9-7764-44e5-8925-55b94027d6b9.mp4

**Comment by g3om3tryYT** [comment]
okay, I fixed it on duckstation by clearing the save file, I think it was some error with the emulator as I had no issues before I had turned the resolution up, so some issue there. I still don't know why it isn't working on wiisxrx.

**Comment by cuckydev** [comment]
I have never experienced this myself in Duckstation, and seeing as clearing your preferences fixed it, it is likely that you messed with the settings to break it somehow. I otherwise don't care about homebrew emulators, since those tend to cut corners for performance and have very low compatibility.
