### ISSUE TITLE
Something about mods

### ISSUE THREAD

**Issue by LuisARVnzla** [cuckydev/PSXFunkin#24]
firstly, excellent job porting the game to psx, in the description of the last release it says that the VS Tricky mod is available but it doesn't appear to me, I play on POPStarter. Would you have thought of adding the mod of sarvente to others? :).

**Comment by cuckydev** [comment]
the last release says that vs kapi is available, which it is (if you press triangle because it wasn't complete, next release won't be like that). vs tricky will come in the next release, but I want to finish some other stuff (week 1 bg and cleanup week 6). I don't plan on adding more mods myself at the moment
